### ISSUE TITLE
Feature request: loading filament - cooldown after load

### ISSUE THREAD

**Issue by nigeljohnson73** [prusa3d/Original-Prusa-MINI#25] opened 2020-05-22 21:22 UTC
You have to select a filament regardless of the current nozzle temp so it will heat up (even from cold), but you should also automatically cool down after the load as well... or remove the option to heat so that people know they have to to do it and stop the heating before walking away leaving the hot-end hot.

**Comment by JohnnyDeer** [comment] 2020-06-15 11:34
Hi @nigeljohnson73 , this issue is related to firmware and is duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/439 and https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/221 . I'll close this one.

**Closed by JohnnyDeer** 2020-06-15 11:34 UTC
