### ISSUE TITLE
Random Print Positioning

### ISSUE THREAD

**Issue by KlausKraemer** [prusa3d/Original-Prusa-MINI#65] opened 2022-12-31 08:41 UTC
Is it thinkable that prints could be printed at random positions?

Most prints are printed in the middle of the print bed. So naturally the wear on PEI coating is concentrated at the center of the print bed. And it's not even restricted to the print bed. It's the same with guide rails and tooth belts.

So randomly placing a print could take some wear of multiple printer parts.

**Comment by Prusa-Support** [comment] 2023-01-31 13:52
Thanks for the suggestion but please mind the print positioning solely depends on Prusa Slicer.
This issue shouldn't be posted here but in [prusa3d/PrusaSlicer](https://github.com/prusa3d/PrusaSlicer) repository.
Also please notice, it is a duplicate of issue https://github.com/prusa3d/PrusaSlicer/issues/320.

Other than this, I would recommend printing in the middle of the bed, and rather avoid printing close to the edges if you can.
Heat dissipation is stronger near the edge, so the adhesion of the object could be weaker, and the object cooling could be a bit too fast too. In fact, often it helps if you print large objects (reaching the edge) with a slightly higher bed temperature.

I hope you will find my advice useful.
Now please allow me to close this issue as unrelated to this repository and as a duplicate.

Michele Moramarco
Prusa Research

**Closed as completed by Prusa-Support** 2023-01-31 13:52 UTC
