### ISSUE TITLE
Feature request: access the menus system while "Remote Printing"

### ISSUE THREAD

**Issue by nigeljohnson73** [prusa3d/Original-Prusa-MINI#28] opened 2020-05-22 21:28 UTC
I love the OctoPrint logo when it's connected, but you cannot access the menus so, for example, you cannot load filament. You need to power cycle the printer do the load, then go back to octoprint to reconnect.

**Comment by JohnnyDeer** [comment] 2020-06-15 11:30
Hi @nigeljohnson73 , this issue is related to firmware and is duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/360. I'll close this one.

**Closed by JohnnyDeer** 2020-06-15 11:30 UTC
