### ISSUE TITLE
STOP button during Purge/Load/Unload

### ISSUE THREAD

**Issue by re490** [prusa3d/Original-Prusa-MINI#44] opened 2021-02-10 01:25 UTC
On my MINI+ (firmware 4.3.0 and prior) there is a STOP button displayed at the bottom of the screen during Purge/Load/Unload operations but it can't be selected.  It would be convenient to be able to stop these operations.

**Comment by JohnnyDeer** [comment] 2021-02-11 07:55
Hi @re490, this issue should be in Buddy FW repository and is duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/370 . I´m closing this one, thank you for understanding.

**Closed by JohnnyDeer** 2021-02-11 07:55 UTC
