### ISSUE TITLE
Bed heating up when unloading filament

### ISSUE THREAD

**Issue by hemdrup** [prusa3d/Original-Prusa-MINI#37] opened 2020-12-20 15:39 UTC
Why does the bed heat up when unloading filament? (This is not when printing, but directly from the home menu)

Prusa Mini+ , version 4.2.1

 https://youtu.be/dRz50qD_JEE

**Comment by JohnnyDeer** [comment] 2021-01-13 07:42
Hi @hemdrup, this issue should be in Prusa-Firmware-Buddy repository and its duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/706
I´m closing this issue.

**Closed by JohnnyDeer** 2021-01-13 07:42 UTC
